# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kieran McNairn
email: thekieran@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  By day, a digital project manager with one of the fastest growing web agencies in the country. By night, a determined autodidact learning how GNU/Linux, programming, and the web works with Ruby, Sinatra, books and videos.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://keerin.github.io" # the base hostname & protocol for your site
twitter_username: thekieran
github_username:  keerin

# Build settings
markdown: kramdown
permalink: pretty
